name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest-m
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6
      - run: gradle build --no-daemon
